import "@/styles/globals.css";

import { Poppins } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import Navbar from "../_components/Navbar";
import SideBar from "../_components/SideBar";
import { Toaster } from "sonner";

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "edu track admin website",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`flex h-[100dvh] flex-col ${font.className}`}>
        <TRPCReactProvider>
          <Toaster duration={2000} richColors position="top-right" />
          <Navbar />
          <div className="flex flex-1 gap-4 p-4">
            <div className="hidden md:flex">
              <SideBar />
            </div>
            <div className="flex-[5]">{children}</div>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
